### ISSUE TITLE
Automate OpenVR updating

### ISSUE THREAD

**Issue by stefnotch** [FlaxCommunityProjects/FlaxVR#2]
The underlying OpenVR library changes every once in a while. It might be neat to be able to automatically update it.
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_api.cs
https://github.com/ValveSoftware/openvr/blob/master/bin/win64/openvr_api.dll

**Comment by klukule** [comment]
OpenVR isn't super required to be as updated as possible, since it's backwards compatible. I wouldn't also auto-update because there could be some breaking changes in C# wrapper, so it's probably just easier to periodically update it.

**Comment by stefnotch** [comment]
Ok, let's stick with periodically updating OpenVR then.
